# Form implementation generated from reading ui file 'weathersecond.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_weathersecond(object):
    def setupUi(self, weathersecond):
        weathersecond.setObjectName("weathersecond")
        weathersecond.resize(333, 428)
        weathersecond.setMinimumSize(QtCore.QSize(333, 428))
        weathersecond.setMaximumSize(QtCore.QSize(333, 428))
        self.weather_type = QtWidgets.QLabel(parent=weathersecond)
        self.weather_type.setGeometry(QtCore.QRect(70, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.weather_type.setFont(font)
        self.weather_type.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weather_type.setObjectName("weather_type")
        self.city_name = QtWidgets.QLabel(parent=weathersecond)
        self.city_name.setGeometry(QtCore.QRect(60, 50, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.city_name.setFont(font)
        self.city_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.city_name.setObjectName("city_name")
        self.temp_main = QtWidgets.QLabel(parent=weathersecond)
        self.temp_main.setGeometry(QtCore.QRect(70, 190, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temp_main.setFont(font)
        self.temp_main.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.temp_main.setObjectName("temp_main")
        self.temp_max = QtWidgets.QLabel(parent=weathersecond)
        self.temp_max.setGeometry(QtCore.QRect(70, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temp_max.setFont(font)
        self.temp_max.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.temp_max.setObjectName("temp_max")
        self.temp_min = QtWidgets.QLabel(parent=weathersecond)
        self.temp_min.setGeometry(QtCore.QRect(70, 310, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temp_min.setFont(font)
        self.temp_min.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.temp_min.setObjectName("temp_min")
        self.back_button = QtWidgets.QPushButton(parent=weathersecond)
        self.back_button.setGeometry(QtCore.QRect(20, 360, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")

        self.retranslateUi(weathersecond)
        QtCore.QMetaObject.connectSlotsByName(weathersecond)

    def retranslateUi(self, weathersecond):
        _translate = QtCore.QCoreApplication.translate
        weathersecond.setWindowTitle(_translate("weathersecond", "Weather App"))
        self.weather_type.setText(_translate("weathersecond", "Weather Type"))
        self.city_name.setText(_translate("weathersecond", "City"))
        self.temp_main.setText(_translate("weathersecond", "Temperature"))
        self.temp_max.setText(_translate("weathersecond", "temp max"))
        self.temp_min.setText(_translate("weathersecond", "temp min"))
        self.back_button.setText(_translate("weathersecond", "Back"))


if __name__ == "__main__":
    import sys
    print('asfsda')
    app = QtWidgets.QApplication(sys.argv)
    weathersecond = QtWidgets.QWidget()
    ui = Ui_weathersecond()
    ui.setupUi(weathersecond)
    weathersecond.show()
    sys.exit(app.exec())
